from django.db import models


class MessageType(models.TextChoices):
    """
    Enumeration of possible message types.

    USER: Message sent by the human user
    BOT: Response generated by the weather bot
    SYSTEM: Automated system notification or alert
    """

    USER = "USER", "User Message"
    BOT = "BOT", "Bot Response"
    SYSTEM = "SYSTEM", "System Message"


class TemperatureUnit(models.TextChoices):
    """
    Temperature unit preferences.

    CELSIUS: Metric system (°C)
    FAHRENHEIT: Imperial system (°F)
    KELVIN: Scientific/absolute scale (K)
    """

    CELSIUS = "C", "Celsius"
    FAHRENHEIT = "F", "Fahrenheit"
    KELVIN = "K", "Kelvin"


class WindSpeedUnit(models.TextChoices):
    """
    Wind speed unit preferences.

    KMH: Kilometers per hour
    MPH: Miles per hour
    MS: Meters per second
    """

    KMH = "kmh", "Kilometers per hour"
    MPH = "mph", "Miles per hour"
    MS = "ms", "Meters per second"
