# Generated by Django 6.0 on 2025-12-09 00:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Unique fingerprint ID from Fingerprint JS API. This identifies the browser/device.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the client's most recent activity",
                    ),
                ),
                (
                    "total_requests",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of weather/chat requests made by this client",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser user agent string for analytics and debugging",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="City name (e.g., 'London', 'New York', 'Tokyo')",
                        max_length=255,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code (e.g., 'GB', 'US', 'JP')",
                        max_length=2,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Geographic latitude (-90 to 90 degrees). Example: 51.507351 for London",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Geographic longitude (-180 to 180 degrees). Example: -0.127758 for London",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this client has searched for this city",
                    ),
                ),
                (
                    "last_searched",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the most recent search for this city",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the client has marked this city as a favorite",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client who searched for this city",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["-last_searched"],
                "unique_together": {("client", "name", "country_code")},
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this conversation was started",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the most recent message in this conversation",
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of messages (user + bot) in this conversation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this conversation is currently active. Inactive conversations can be archived.",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client who initiated this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("USER", "User Message"),
                            ("BOT", "Bot Response"),
                            ("SYSTEM", "System Message"),
                        ],
                        default="USER",
                        help_text="Type of message: USER (from client), BOT (response), or SYSTEM (notification)",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual message text or bot response content"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Exact timestamp when this message was created",
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback: whether the bot's response was helpful (True/False/None)",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation this message is part of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_conversation",
                        to="core.conversation",
                    ),
                ),
                (
                    "related_city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: The city being discussed in this message for context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_related_city",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature_unit",
                    models.CharField(
                        choices=[
                            ("C", "Celsius"),
                            ("F", "Fahrenheit"),
                            ("K", "Kelvin"),
                        ],
                        default="C",
                        help_text="Preferred temperature unit: Celsius (C), Fahrenheit (F), or Kelvin (K)",
                        max_length=1,
                    ),
                ),
                (
                    "wind_speed_unit",
                    models.CharField(
                        choices=[
                            ("kmh", "Kilometers per hour"),
                            ("mph", "Miles per hour"),
                            ("ms", "Meters per second"),
                        ],
                        default="kmh",
                        help_text="Preferred wind speed unit: km/h, mph, or m/s",
                        max_length=3,
                    ),
                ),
                (
                    "show_forecast",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to display weather forecast in addition to current weather",
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to enable weather alert notifications for saved cities",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        help_text="The client these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="core.client",
                    ),
                ),
                (
                    "default_city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Default city to display when the user opens the app",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_users",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Brief alert headline (e.g., 'Thunderstorm Warning', 'Heat Advisory')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the weather alert and recommended actions"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("SEVERE", "Severe"),
                        ],
                        default="MODERATE",
                        help_text="Alert severity level: LOW, MODERATE, HIGH, or SEVERE",
                        max_length=10,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When this alert becomes active"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="When this alert expires or is no longer valid"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this alert is currently active. Can be manually deactivated.",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="The city this weather alert applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Alert",
                "verbose_name_plural": "Weather Alerts",
                "ordering": ["-severity", "-start_time"],
            },
        ),
    ]
